### ISSUE TITLE
ERROR 1: PROJ: proj_identify: Cannot find proj.db

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/pa-aa-bfa-drought#5]
When I get the following warning below:
```
python src/main.py
#> ERROR:fiona._env:PROJ: proj_identify: C:\Program Files\PostgreSQL\14\share\contrib\postgis-3.2\proj\proj.db contains # DATABASE.LAYOUT.VERSION.MINOR = 0 whereas a number >= 2 is expected. It comes from another PROJ installation
```

On windows I  have  a `PROJ_LIB`  system environment variable configured for `PostgreSQL`. I think this is likely the issue.

If I don't change anything, a related error completely stops `python src/monitor_trigger.py`  from running. Like the warning says it seems to be an issue of the environment variable coming from somewhere outside of the venv.

I think we want might want to set the `PROJ_LIB` or `PROJ` variable locally in the venv. From what I read this is automatically done when using `conda`,   The question is where to set it?

As an experiment I just tried: 
```
$env:PROJ_LIB = 'C:\Users\zack.arno\Documents\GeoCrunch\chd\chd_projects\pa-aa-bfa-drought\.venv\Scripts\'  
python src/monitor_trigger.py
#> ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
#> ERROR 1: PROJ: proj_identify: Cannot find proj.db
#> ERROR 1: PROJ: proj_identify: Cannot find proj.db
#> ERROR 1: PROJ: proj_identify: Cannot find proj.db
#> ERROR 1: PROJ: proj_identify: Cannot find proj.db
```
To me it seems like the new `PROJ_LIB` var is recognized (as it no longer is pointing to my `PostgreSQL` directory), but it is probably pointing to the wrong place.

Any ideas @Tinkaa ?

**Comment by zackarno** [comment]
I have a lead:

The following yields no warning
```
$env:PROJ_LIB = 'C:\Users\zack.arno\Documents\GeoCrunch\chd\chd_projects\pa-aa-bfa-drought\.venv\Lib\site-packages\osgeo\data\proj'
python src/main.py
```
If i then run `python src/monitor_trigger.py` it seems to bypass the above `proj.db`  error, but now on to the **next error** which seems to be unrelated.
```
C:\Users\zack.arno\Documents\GeoCrunch\chd\chd_projects\pa-aa-bfa-drought\.venv\lib\site-packages\numpy\lib\nanfunctions.py:1879: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
C:\Users\zack.arno\Documents\GeoCrunch\chd\chd_projects\pa-aa-bfa-drought\.venv\lib\site-packages\numpy\lib\nanfunctions.py:1584: RuntimeWarning: All-NaN slice encountered
  result = np.apply_along_axis(_nanquantile_1d, axis, a, q,
Traceback (most recent call last):
  File "C:\Users\zack.arno\Documents\GeoCrunch\chd\chd_projects\pa-aa-bfa-drought\src\monitor_trigger.py", line 284, in <module>
    compute_trigger_bfa()
  File "C:\Users\zack.arno\Documents\GeoCrunch\chd\chd_projects\pa-aa-bfa-drought\src\monitor_trigger.py", line 69, in compute_trigger_bfa
    df_stats_aoi_bavg = compute_stats_iri(
  File "C:\Users\zack.arno\Documents\GeoCrunch\chd\chd_projects\pa-aa-bfa-drought\src\monitor_trigger.py", line 255, in compute_stats_iri
    df_stats_aoi_bavg["pred_seas"] = df_stats_aoi_bavg.apply(
  File "C:\Users\zack.arno\Documents\GeoCrunch\chd\chd_projects\pa-aa-bfa-drought\.venv\lib\site-packages\pandas\core\frame.py", line 8833, in apply
    return op.apply().__finalize__(self, method="apply")
  File "C:\Users\zack.arno\Documents\GeoCrunch\chd\chd_projects\pa-aa-bfa-drought\.venv\lib\site-packages\pandas\core\apply.py", line 727, in apply
    return self.apply_standard()
  File "C:\Users\zack.arno\Documents\GeoCrunch\chd\chd_projects\pa-aa-bfa-drought\.venv\lib\site-packages\pandas\core\apply.py", line 851, in apply_standard
    results, res_index = self.apply_series_generator()
  File "C:\Users\zack.arno\Documents\GeoCrunch\chd\chd_projects\pa-aa-bfa-drought\.venv\lib\site-packages\pandas\core\apply.py", line 867, in apply_series_generator   
    results[i] = self.f(v)
  File "C:\Users\zack.arno\Documents\GeoCrunch\chd\chd_projects\pa-aa-bfa-drought\src\monitor_trigger.py", line 257, in <lambda>
    int((x["F"] + relativedelta(months=int(x["L"]))).strftime("%-m"))
  File "pandas\_libs\tslibs\timestamps.pyx", line 1218, in pandas._libs.tslibs.timestamps.Timestamp.strftime
ValueError: Invalid format string
```
I think the original error posted in this issue is **solved** by setting the new env variable path. Perhaps we can isolate this new error and open a new issue?

**Comment by Tinkaa** [comment]
Nice! Good job. 

I think I also solved the new error, apparently `.strftime("%-m")` is platform dependent and doesn't work on Windows.. (I guess we should think about making automated tests across platforms) 
But hopefully solved it in #6 so great if you could test that!

**Comment by zackarno** [comment]
same issue with `ds_iri_dom = iri_dom.load()`

```
#> ERROR 1: PROJ: proj_create_from_database: C:\Program Files\PostgreSQL\14\share\contrib\postgis-3.2\proj\proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 0 whereas a number >= 2 is expected. It comes from another PROJ installation.

```

**Comment by t-downing** [comment]
Closing as IRI global seasonal forecast will no longer be used for trigger.
