### ISSUE TITLE
constants - create_country_config

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/pa-aa-bfa-drought#9]
Seems too simple not to work, but code below creates the error

https://github.com/OCHA-DAP/pa-aa-bfa-drought/blob/f25021f3983d02acfed4a4e7f29f26ad80fe32e1/src/constants.py#L1-L4

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zackarno/Documents/CHD/repos/pa-aa-bfa-drought/.venv/lib/python3.11/site-packages/aatoolbox/config/countryconfig.py", line 121, in create_country_config
    return CountryConfig(**parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zackarno/Documents/CHD/repos/pa-aa-bfa-drought/.venv/lib/python3.11/site-packages/pydantic/main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for CountryConfig
codab.custom_layer_names
  Field required [type=missing, input_value={'hdx_dataset_name': 'bfa...', 'admin_level_max': 3}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
```

**Comment by turnerm** [comment]
Try pinning pydantic to <2.0 in the requirements

**Comment by t-downing** [comment]
Closing as `aatoolbox` no longer being used for loading CODABs.
